apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rutorrent.fullname" . }}-data
  labels:
    {{- include "rutorrent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
