apiVersion: v1
kind: Service
metadata:
  name: {{ include "rutorrent.fullname" . }}-http
  labels:
    {{- include "rutorrent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rutorrent.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rutorrent.fullname" . }}-rtorrent
  labels:
    {{- include "rutorrent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.rtorrent.type }}
  ports:
    - port: {{ .Values.service.rtorrent.dht.port }}
      targetPort: dht
      protocol: UDP
      name: dht
      {{- if .Values.service.rtorrent.dht.nodePort }}
      nodePort: {{ .Values.service.rtorrent.dht.nodePort }}
      {{- end }}
    - port: {{ .Values.service.rtorrent.rtorrent.port }}
      targetPort: rtorrent
      protocol: TCP
      name: rtorrent-tcp
      {{- if .Values.service.rtorrent.rtorrent.nodePort }}
      nodePort: {{ .Values.service.rtorrent.rtorrent.nodePort }}
      {{- end }}
    - port: {{ .Values.service.rtorrent.rtorrent.port }}
      targetPort: rtorrent
      protocol: UDP
      name: rtorrent-udp
      {{- if .Values.service.rtorrent.rtorrent.nodePort }}
      nodePort: {{ .Values.service.rtorrent.rtorrent.nodePort }}
      {{- end }}
  selector:
    {{- include "rutorrent.selectorLabels" . | nindent 4 }}
