#!/bin/sh

set -e

umask 0077

mkdir -p \
  /tmp/nginx \
  /tmp/nginx/body \
  /tmp/nginx/fastcgi \
  /tmp/nginx/proxy \
  /tmp/nginx/scgi \
  /tmp/nginx/uwsgi

exec /usr/sbin/nginx -c /config/nginx/nginx.conf
