#!/bin/sh

umask 0077

mkdir -p \
  /run/nginx \
  /run/nginx/body \
  /run/nginx/fastcgi \
  /run/nginx/proxy \
  /run/nginx/scgi \
  /run/nginx/uwsgi

exec /usr/sbin/nginx -c /config/nginx/nginx.conf
